language: python
python:
- 3.2
- 3.3
- 3.4
install:
- pip install -r requirements.txt
script:
- pep8 .
- nosetests --with-coverage --cover-package=conflib
after_success:
- coveralls
notifications:
  email: false
  irc:
    channels:
    - irc.oftc.net#akerl
    template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
