language: python
python:
- 3.2
- 3.3
install:
- pip install -r requirements.txt
script:
- pep8 .
- nosetests --with-coverage --cover-package=conflib
after_success:
- coveralls
notifications:
  email: false
  irc:
    channels:
    - secure: AyW/jUgg1dIGk22AzKBY0DPRaK/5PmL3mEc2XcqMm0zOCcFvnc82mzBU5yC+HtCQ1qDGKSiHUOEExmpg8xzI1FgwRggbLHeMUWPmZyvq0DvbULAdPXLYUWEXcSlZv1pNtKXdtx2jl69Sq8PEIvHdHcQGNdmI3ilggTcE2grdEUc=
    template:
    - "%{repository}/%{branch}/%{build_number}: %{message} -- %{build_url}"
